Lending and authorization
owner6/foodOnline-front pull request #1
Opened 2023-11-16 20:11 UTC by owner6

2023-11-17 22:39 UTC, dever4eg requested changes

2023-11-17 22:39 UTC, dever4eg commented on public/index.html
> +  </div>
Щось зайве тут

2023-11-17 22:39 UTC, dever4eg commented on package.json
> +    "@material/web": "^1.0.0",
Передивись бібліотеки зайві прибери

2023-11-17 22:39 UTC, dever4eg commented on src/assets/styles/styles.css
> +/*# sourceMappingURL=styles.css.map */
Це треба?

2023-11-17 22:39 UTC, dever4eg commented on src/assets/styles/styles.css.map
> +{"version":3,"sources":[],"names":[],"mappings":"","file":"styles.css"}
Це треба?

2023-11-17 22:39 UTC, dever4eg commented on src/assets/styles/styles.css.map
> +{"version":3,"sources":[],"names":[],"mappings":"","file":"styles.css"}
.map файли наврядчи треба

2023-11-17 22:39 UTC, dever4eg commented on src/components/ui/v-popup.vue
> +<template>
v-popup - название как просто попап, общее название
- или нужно переименовать на v-auth-popup
- или сделать его переиспользуемьім и не связанньім с авторизацией

2023-11-17 22:39 UTC, dever4eg commented on src/components/ui/v-popup.vue
> +      API_URL: "http://localhost:3000",
Змінну цю краще кудись винести в окремий файл. Константи чи конфіги.
І взагалі така змінна має підтягуватись з .env файлу почитай як в vue робиться то

2023-11-17 22:39 UTC, dever4eg commented on src/components/ui/v-popup.vue
> +        window.location.reload();
https://v2.vuejs.org/v2/cookbook/client-side-storage.html

2023-11-17 22:39 UTC, dever4eg commented on src/components/ui/v-popup.vue
> +        this.showAuthForm = !this.showAuthForm;
this.showAuthForm = false

2023-11-17 22:39 UTC, dever4eg commented on src/components/ui/v-popup.vue
> +      window.location.reload();
Теж, reload краще не юзати. Виправ так щоб без нього працювало

2023-11-17 22:39 UTC, dever4eg commented on src/router/index.js
> +  if (to.matched.some((record) => record.meta.requiresAuth) && authToken) {
Передивись тут логіку. Щось дивне

2023-11-17 22:39 UTC, dever4eg commented on src/views/my-page-component.vue
> +    API_URL() {
Теж це кудись винеси

2023-11-17 22:39 UTC, dever4eg commented on vue.config.js
> +        additionalData: `@import "@/assets/styles/styles.scss";`,
це треба?

2023-11-18 08:56 UTC, owner6 commented on public/index.html
> +  </div>
formatted code

2023-11-18 11:38 UTC, owner6 commented on package.json
> +    "@material/web": "^1.0.0",
зайві доповнення видалені

2023-11-18 11:39 UTC, owner6 commented on src/assets/styles/styles.css
> +/*# sourceMappingURL=styles.css.map */
тека "styles" видалена

2023-11-18 11:41 UTC, owner6 commented on src/assets/styles/styles.css.map
> +{"version":3,"sources":[],"names":[],"mappings":"","file":"styles.css"}
видалена тека "styles"

2023-11-18 19:04 UTC, owner6 commented on src/components/ui/v-popup.vue
> +<template>
перейменував

2023-11-18 19:05 UTC, owner6 commented on src/components/ui/v-popup.vue
> +        this.showAuthForm = !this.showAuthForm;
виконав

2023-11-19 10:19 UTC, owner6 commented on src/components/ui/v-popup.vue
> +      window.location.reload();
частково виправив

2023-12-07 10:30 UTC, merged